import React, { useEffect, useMemo, useState } from "react";
import { Bar, Doughnut, Line } from "react-chartjs-2";
import { Chart as ChartJS, CategoryScale, LinearScale, BarElement, LineElement, PointElement, ArcElement, Tooltip, Legend } from "chart.js";
import { Activity, Bot, CheckCircle2, ChevronRight, ChartNoAxesCombined, Database, FileClock, Gauge, LockKeyhole, MessageSquare, Radar, RefreshCw, ShieldCheck, SlidersHorizontal, Sparkles, Users } from "lucide-react";
import MetricCard from "../components/common/MetricCard";
import ThreatFeed from "../components/dashboard/ThreatFeed";
import PipelineVisualizer from "../components/dashboard/PipelineVisualizer";
import PricingPage from "../components/saas/PricingPage";
import { shieldApi } from "../api/shieldApi";

ChartJS.register(CategoryScale, LinearScale, BarElement, LineElement, PointElement, ArcElement, Tooltip, Legend);

export function Kpis({ analytics }) {
  const cards = [["PROMPTS SCANNED", analytics.scanned, "+12.4%", Gauge], ["ATTACKS THWARTED", analytics.blocked, "+8.7%", ShieldCheck], ["HONEYPOT CAPTURES", analytics.honeypots, "+21.2%", Radar], ["AVG. LATENCY", `${analytics.latency_ms}ms`, "-0.4ms", Activity]];
  return <section className="kpis">{cards.map(([label, value, change, Icon]) => <MetricCard key={label} label={label} value={Number.isFinite(value) ? value.toLocaleString() : value} change={change} Icon={Icon} />)}</section>;
}

export function CommandCenter({ analytics, events, onNavigate }) {
  const score = Math.max(0, Math.min(100, 96 - Math.round((analytics.latency_ms || 0) > 5 ? 8 : 0) - (analytics.blocked > analytics.scanned * .4 ? 4 : 0)));
  const quota = Math.min(100, (analytics.scanned / 10000) * 100);
  return <><Kpis analytics={analytics} /><div className="overview-grid"><section className="panel welcome-panel"><div className="section-kicker"><ShieldCheck size={14} /> PROTECTION FABRIC</div><h2>Your AI perimeter is protected.</h2><p>NexusShield is actively inspecting inbound prompts, model outputs, and conversational context across seven defensive layers.</p><div className="health-row"><span className="pulse" />Pipeline healthy <b>99.98% uptime</b></div><button onClick={() => onNavigate("playground")}>OPEN SECURITY PLAYGROUND <ChevronRight size={15} /></button></section><ThreatFeed events={events} onViewAll={() => onNavigate("audit")} /></div><div className="innovation-grid"><section className="panel posture-card"><div className="panel-heading"><div><span className="section-kicker"><Sparkles size={14} /> EXPLAINABLE READINESS</span><h2>Security posture score</h2></div><span className="posture-score">{score}</span></div><div className="posture-ring" style={{ "--score": `${score * 3.6}deg` }}><strong>{score}</strong><span>/100</span></div><div className="posture-signals"><span><CheckCircle2 size={13} /> Encryption verified</span><span><CheckCircle2 size={13} /> Tenant isolation active</span><span><CheckCircle2 size={13} /> Edge latency optimal</span></div></section><section className="panel quota-card"><div className="panel-heading"><div><span className="section-kicker"><Gauge size={14} /> TENANT QUOTA</span><h2>Developer Free plan</h2></div><span className="secure-badge">{Math.round(quota)}% USED</span></div><div className="quota-bar"><i style={{ width: `${quota}%` }} /></div><p>{analytics.scanned.toLocaleString()} of 10,000 monthly scans consumed.</p><button onClick={() => onNavigate("billing")}>VIEW PLAN & USAGE <ChevronRight size={14} /></button></section></div><section className="panel coverage-panel"><div className="panel-heading"><div><span className="section-kicker"><LockKeyhole size={14} /> LAYER COVERAGE</span><h2>Seven layers active</h2></div><span className="secure-badge">ENCRYPTED AT REST</span></div><div className="layer-cards">{["Rate limiting", "PII scrubbing", "Context memory", "Vector + BERT", "Output shield", "Shadow + honeypot", "Feedback loop"].map((name, i) => <div key={name}><span>{String(i + 1).padStart(2, "0")}</span><b>{name}</b><CheckCircle2 size={16} /></div>)}</div></section></>;
}

export function SecurityPlayground({ analytics, refresh, notify }) {
  const [prompt, setPrompt] = useState(""); const [result, setResult] = useState(null); const [logs, setLogs] = useState([]); const [loading, setLoading] = useState(false);
  const scan = async () => {
    if (!prompt.trim() || loading) return; setLoading(true); setResult(null); setLogs([]);
    try {
      const data = await shieldApi.scan({ prompt, session_id: "dashboard-session", client_id: "dashboard-user" }); setResult(data);
      if (data.decision !== "allowed") notify(`${data.decision === "honeypot" ? "High-severity attack trapped" : "Threat blocked"} from dashboard-user`);
      (data.logs || []).forEach((_, index) => setTimeout(() => setLogs((data.logs || []).slice(0, index + 1)), 240 * index)); await refresh();
    } catch { setResult({ decision: "error", response: "API unavailable. Start the FastAPI service on port 8000.", logs: [] }); }
    finally { setLoading(false); }
  };
  return <><Kpis analytics={analytics} /><div className="playground-grid"><section className="panel chat-panel"><div className="panel-heading"><div><span className="section-kicker"><MessageSquare size={14} /> INPUT GATEWAY</span><h2>Test a prompt</h2></div><span className="secure-badge"><LockKeyhole size={13} /> ENCRYPTED</span></div><div className="chat-history">{result ? <div className={`response-card ${result.decision}`}><div className="response-title"><Bot size={16} /> {result.decision === "honeypot" ? "HONEYPOT TRAPPED" : result.decision.toUpperCase()}</div><pre>{JSON.stringify({ decision: result.decision, scrubbed_response: result.response, event_id: result.event_id, latency_ms: result.latency_ms }, null, 2)}</pre></div> : <div className="empty-chat"><div className="empty-icon"><Sparkles size={22} /></div><b>Send a prompt to begin</b><span>Every request is inspected across all 7 defensive layers.</span></div>}</div><div className="composer"><textarea maxLength="10000" value={prompt} onChange={(e) => setPrompt(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); scan(); } }} placeholder="Try a normal question or a simulated attack..." /><div className="composer-footer"><span>{prompt.length.toLocaleString()} / 10,000 characters · ↵ Enter to scan</span><button onClick={scan} disabled={loading}>{loading ? "SCANNING..." : "SCAN PROMPT"} <ChevronRight size={15} /></button></div></div></section><PipelineVisualizer logs={logs} latency={result?.latency_ms || analytics.latency_ms} /></div></>;
}

export function HoneypotConsole({ honeypots }) {
  const [selected, setSelected] = useState(honeypots[0] || null); useEffect(() => setSelected(honeypots[0] || null), [honeypots]);
  const rows = honeypots.length ? honeypots : [{ id: "demo-room", client_id: "—", session_id: "Run a scan", signature: "Waiting for detection", started_at: new Date().toISOString(), status: "STANDBY" }];
  return <section className="content-section"><div className="section-intro"><div><span className="section-kicker"><Radar size={14} /> DECEPTION NETWORK</span><h2>Trapped hackers & live interception</h2><p>Suspicious actors remain in convincing decoy rooms while their tactics are recorded and encrypted.</p></div><span className="secure-badge"><span className="pulse" /> {honeypots.length} ACTIVE TRAPS</span></div><div className="table-wrap panel"><table><thead><tr><th>TRAP ROOM</th><th>ACTOR / IP</th><th>SESSION ID</th><th>THREAT SIGNATURE</th><th>STARTED</th><th>STATUS</th></tr></thead><tbody>{rows.map((trap, i) => <tr className="clickable-row" onClick={() => setSelected(trap)} key={trap.id}><td><span className="room"><Bot size={15} /> Ghost Room {String(i + 1).padStart(2, "0")}</span></td><td>{trap.client_id}</td><td className="mono">{trap.session_id}</td><td className="orange">{trap.signature}</td><td>{new Date(trap.started_at).toLocaleString()}</td><td><span className={trap.status === "ACTIVE" ? "active-pill" : "muted-pill"}><span className="pulse" /> {trap.status}</span></td></tr>)}</tbody></table></div><div className="interception panel"><div><span className="section-kicker"><Users size={14} /> LIVE INTERCEPTION VIEW</span><h3>{selected ? `Ghost Room · ${selected.signature}` : "Select a trapped session"}</h3><div className="fake-chat"><div><b>Hacker</b><span>{selected?.last_message || "No active session selected."}</span></div><div><b>Decoy AI</b><span>Access verified. Please provide the next command so I can continue helping.</span></div></div><p>Layer 7 is recording this exchange, encrypting the trace, and learning new attack signatures without redeployment.</p></div><div className="learning-stats"><b>18<small>patterns learned</small></b><b>94.2%<small>confidence</small></b><b>2.1s<small>last update</small></b></div></div></section>;
}

export function ThreatAnalytics({ analytics }) {
  const labels = Object.keys(analytics.threats || {}).length ? Object.keys(analytics.threats) : ["Jailbreak", "PII leakage", "Toxicity", "DoS"]; const values = labels.map((label) => analytics.threats[label] || 0);
  const options = { responsive: true, plugins: { legend: { labels: { color: "#90a6a5" } } }, scales: { x: { ticks: { color: "#789092" }, grid: { color: "#1d3030" } }, y: { ticks: { color: "#789092" }, grid: { color: "#1d3030" } } } };
  return <section className="content-section"><Kpis analytics={analytics} /><div className="charts-grid"><div className="panel chart-card"><span className="section-kicker"><ChartNoAxesCombined size={14} /> THREAT MIX</span><h2>Detected threat categories</h2><Bar data={{ labels, datasets: [{ label: "Detections", data: values, backgroundColor: ["#61d6b1", "#e2a161", "#d97e70", "#7797da"], borderRadius: 4 }] }} options={options} /></div><div className="panel chart-card"><span className="section-kicker"><Activity size={14} /> LAYER EFFICIENCY</span><h2>Detection by layer</h2><Doughnut data={{ labels: Object.keys(analytics.layers || {}), datasets: [{ data: Object.values(analytics.layers || {}), backgroundColor: ["#61d6b1", "#e2a161", "#7797da", "#d97e70"], borderColor: "#112021" }] }} options={{ plugins: { legend: { position: "bottom", labels: { color: "#90a6a5" } } } }} /></div></div><div className="panel chart-card wide-chart"><span className="section-kicker"><Activity size={14} /> TELEMETRY</span><h2>Protection activity</h2><Line data={{ labels: ["00:00", "04:00", "08:00", "12:00", "16:00", "20:00"], datasets: [{ label: "Prompts", data: [18, 32, 28, 45, 39, 56], borderColor: "#61d6b1", backgroundColor: "rgba(97,214,177,.12)", fill: true, tension: .35 }] }} options={options} /></div></section>;
}

export function PolicyConfig({ policy, onSave }) {
  const update = (key, value) => onSave({ ...policy, [key]: value });
  return <section className="content-section"><div className="section-intro"><div><span className="section-kicker"><SlidersHorizontal size={14} /> CONTROL PLANE</span><h2>Policy configuration</h2><p>These controls persist in SQLite and apply immediately to the protection fabric.</p></div><span className="secure-badge"><CheckCircle2 size={13} /> SAVED LOCALLY</span></div><div className="policy-grid"><div className="panel policy-card"><h3>Detection sensitivity</h3><label>Vector similarity threshold <output>{Number(policy.similarity_threshold).toFixed(2)}</output><input type="range" min=".5" max=".99" step=".01" value={policy.similarity_threshold} onChange={(e) => update("similarity_threshold", Number(e.target.value))} /></label><p>Prompts at or above this score are treated as suspicious and routed according to your response controls.</p><div className="threshold-scale"><span>Broad catch</span><span>High confidence</span></div></div><div className="panel policy-card"><h3>Response controls</h3>{[["enable_honeypot", "Enable AI honeypot trap", "Route high-confidence attackers to a decoy room."], ["strict_pii", "Strict PII scrubbing", "Mask CNICs, cards, API keys, and passwords."], ["strict_toxicity", "Outbound toxicity filter", "Block unsafe language before it reaches users."], ["auto_block_dos", "Auto-block repeated DoS", "Enforce the sliding-window request threshold."]].map(([key, title, desc]) => <label className="toggle-row" key={key}><span><b>{title}</b><small>{desc}</small></span><button type="button" className={`toggle ${policy[key] ? "on" : ""}`} onClick={() => update(key, !policy[key])}><i /></button></label>)}</div></div></section>;
}

export function AuditLog({ events, refresh }) {
  const [decrypted, setDecrypted] = useState(false);
  const download = (format) => { const rows = events.map((event) => format === "csv" ? [event.id, event.created_at, event.signature, event.decision, event.similarity, event.latency_ms].join(",") : JSON.stringify(event)).join("\n"); const content = format === "csv" ? `event_id,timestamp,signature,decision,similarity,latency_ms\n${rows}` : `[${rows}]`; const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([content], { type: format === "csv" ? "text/csv" : "application/json" })); link.download = `nexusshield-audit.${format}`; link.click(); URL.revokeObjectURL(link.href); };
  return <section className="content-section"><div className="section-intro"><div><span className="section-kicker"><FileClock size={14} /> FORENSIC STORAGE</span><h2>Encrypted audit log</h2><p>Raw traces are encrypted with AES-256-CBC before persistence. Only metadata is shown here.</p></div><div className="audit-actions"><label className="decrypt-switch"><input type="checkbox" checked={decrypted} onChange={(e) => setDecrypted(e.target.checked)} /> {decrypted ? "SHOW METADATA" : "SIMULATE DECRYPTION"}</label><button className="outline-button refresh-button" onClick={refresh}><RefreshCw size={14} /> REFRESH</button><button className="outline-button refresh-button" onClick={() => download("json")}>EXPORT JSON</button><button className="outline-button refresh-button" onClick={() => download("csv")}>EXPORT CSV</button></div></div><div className="table-wrap panel"><table><thead><tr><th>EVENT ID</th><th>TIMESTAMP</th><th>{decrypted ? "PROMPT PREVIEW" : "AES-256 PAYLOAD"}</th><th>DECISION</th><th>SIMILARITY</th><th>LATENCY</th><th>FEEDBACK</th></tr></thead><tbody>{events.map((event) => <tr key={event.id}><td className="mono">{event.id}</td><td>{new Date(event.created_at).toLocaleString()}</td><td className="mono">{decrypted ? (event.prompt || "").slice(0, 45) : `U2FsdGVkX1${btoa(event.id).slice(0, 16)}...`}</td><td><span className={`decision-pill ${event.decision}`}>{event.decision}</span></td><td>{(event.similarity * 100).toFixed(1)}%</td><td>{event.latency_ms}ms</td><td>{event.feedback || "Pending"}</td></tr>)}{!events.length && <tr><td colSpan="7" className="empty-state">No encrypted events stored yet.</td></tr>}</tbody></table></div></section>;
}

export function ApiKeyManager() {
  const [keys, setKeys] = useState([]); const [name, setName] = useState(""); const [revealed, setRevealed] = useState("");
  const load = () => shieldApi.keys().then(setKeys).catch(() => {});
  useEffect(load, []);
  const create = async (event) => { event.preventDefault(); const data = await shieldApi.createKey(name); setRevealed(data.key); setName(""); load(); };
  return <section className="content-section"><div className="section-intro"><div><span className="section-kicker"><LockKeyhole size={14} /> DEVELOPER ACCESS</span><h2>API key manager</h2><p>Provision tenant-isolated keys for external chatbot middleware integrations.</p></div></div><div className="policy-grid"><div className="panel policy-card"><h3>Create an API key</h3><form className="key-form" onSubmit={create}><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Key name, e.g. Production chatbot" required /><button type="submit">GENERATE KEY <ChevronRight size={15} /></button></form>{revealed && <div className="new-key"><small>Copy this key now. It will not be shown again.</small><code>{revealed}</code></div>}</div><div className="panel policy-card"><h3>Your tenant keys</h3>{keys.length ? keys.map((key) => <div className="key-row" key={key.id}><span><b>{key.name}</b><small>{key.prefix}... · {key.revoked_at ? "REVOKED" : "ACTIVE"}</small></span>{!key.revoked_at && <button className="text-button" onClick={() => shieldApi.revokeKey(key.id).then(load)}>Revoke</button>}</div>) : <div className="empty-state">No API keys provisioned.</div>}</div></div></section>;
}

export function TeamManager() {
  const [members, setMembers] = useState([]); const load = () => shieldApi.team().then(setMembers).catch(() => {}); useEffect(load, []);
  return <section className="content-section"><div className="section-intro"><div><span className="section-kicker"><Users size={14} /> ORGANIZATION ADMIN</span><h2>Team members</h2><p>Manage roles inside your isolated tenant workspace.</p></div></div><div className="table-wrap panel"><table><thead><tr><th>MEMBER</th><th>EMAIL</th><th>ROLE</th><th>JOINED</th><th>ACCESS</th></tr></thead><tbody>{members.map((member) => <tr key={member.id}><td>{member.name}</td><td>{member.email}</td><td><select className="role-select" value={member.role} onChange={(e) => shieldApi.updateRole(member.id, e.target.value).then(load)}><option value="admin">Admin</option><option value="developer">Developer</option><option value="auditor">Auditor</option></select></td><td>{new Date(member.created_at).toLocaleDateString()}</td><td><span className="active-pill">AUTHORIZED</span></td></tr>)}</tbody></table></div></section>;
}

export function Billing() {
  const [billing, setBilling] = useState(null); useEffect(() => { shieldApi.billing().then(setBilling).catch(() => {}); }, []);
  const used = billing ? Math.min(100, billing.used / billing.monthly_quota * 100) : 0;
  return <section className="content-section"><div className="section-intro"><div><span className="section-kicker"><Database size={14} /> SUBSCRIPTION CONTROL</span><h2>Billing & subscription</h2><p>Monitor tenant usage and choose the right protection tier.</p></div></div><div className="policy-grid"><div className="panel policy-card"><span className="section-kicker">CURRENT PLAN</span><h2>{billing?.plan || "Loading..."}</h2><div className="quota-bar"><i style={{ width: `${used}%` }} /></div><p>{billing?.used || 0} of {billing?.monthly_quota || 10000} monthly scans consumed.</p><button className="upgrade-button">UPGRADE TO STARTUP PRO <ChevronRight size={15} /></button></div><PricingPage onGetStarted={() => {}} /></div></section>;
}
